### ISSUE TITLE
Looking for the way to make MTCNN return multiple bounding boxes

### ISSUE THREAD

**Issue by Jusya** [davidsandberg/facenet#101]
Hello)
Is it possible for MTCNN to return all bounding boxes with all different faces on an image? If yes, what is the right way to do this?

Waining for respond.
Thank you in advance)

**Comment by davidsandberg** [comment]
Hi,
This should be fairly easy since the call to `detect_face`:
`bounding_boxes, _ = align.detect_face.detect_face(img, minsize, pnet, rnet, onet, threshold, factor)`
returns the detected faces as rows in a numpy array. 
In `align_dataset_mtcnn.py` there is some code to figure out which face (among the detected ones) that is the most relevant, but that could shouldn't be needed then.
