### ISSUE TITLE
Stretched faces after aligning

### ISSUE THREAD

**Issue by nerevar** [davidsandberg/facenet#118]
Hello, David!

After cropping, there are image with correct aspect ratio (face height more then width), and after aligning, face is stretched across the width into square thumbnail. For example, [Brad Pitt](https://yadi.sk/i/DgIDZtXN39AXkH)

Is it OK? Maybe rewrite code to keep aspect ratio and then use rectangled thumbnails?

https://github.com/davidsandberg/facenet/blob/master/src/compare.py#L106-L107

**Comment by crockpotveggies** [comment]
I can't speak for David's code directly, but that's a typical output from face alignment. The goal is to align facial features and, presumably, the network can "learn" the differentiation among the features without having to discover the positioning -- which can take much longer to learn. It's essentially normalizing the input. David might explain this differently.

**Comment by nerevar** [comment]
@crockpotveggies Yes, I think so about normalizing the input, but can the network accept images with different sizes, so feed network with rectangular-cropped faces, which already positioned?

**Comment by crockpotveggies** [comment]
How are the images different sizes? It's a random crop from 186 -> 160 pixels, but the input is still 160 pixels as I understand it.

**Comment by nerevar** [comment]
Yes, now it is square.
I'm asking about different sizes. Is it possible? Fixed 160px height, but different width, for example.

**Comment by crockpotveggies** [comment]
You could pad your input, but this discussion is kind of going beyond the scope of the repository. I suggest hitting up one of the OpenAI Gitter chats, there's a room for deeplearning beginners with a supportive crowd. 
![image](https://cloud.githubusercontent.com/assets/1445295/21998179/1a7146f4-dbe8-11e6-9586-b948367eba5b.png)

**Comment by nerevar** [comment]
Thanks! :smile:

**Comment by yong2khoo-lm** [comment]
Hi @crockpotveggies and @nerevar , can you please elaborate a little bit of the final result (cross-correlated result)?
I do wonder, an originally rectangle face (eg: 145 x 160), if stretched, wouldn't it tamper the face features? 

So, i tested with both situation (if it is a rectangle face instead of a square)
1) stretched face 
2) add black colors to make it square (as below)

![24](https://user-images.githubusercontent.com/51041738/99511527-52d53c80-29c3-11eb-868e-b22fdbab64ac.png)

However, there isn't much help. Worse, adding black padding sometimes generate lower confidence with SVM.

How should i amend it? (thanks in advance)

**Comment by mrkatouei** [comment]
You do this pls for me

در تاریخ چهارشنبه ۱۸ نوامبر ۲۰۲۰،‏ ۱۳:۰۲ Khoo Yong Yong <
notifications@github.com> نوشت:

**Comment by yong2khoo-lm** [comment]
@mrkatouei hi.. ??

**Comment by mrkatouei** [comment]
Hi commit this repo yourself pls

در تاریخ چهارشنبه ۱۸ نوامبر ۲۰۲۰،‏ ۱۵:۱۵ Khoo Yong Yong <
notifications@github.com> نوشت:

**Comment by mrkatouei** [comment]
Send a message in hangout for me to speak

در تاریخ پنجشنبه ۱۹ نوامبر ۲۰۲۰،‏ ۱۱:۵۹ mohamadreza katoueizade <
mr.katouei@gmail.com> نوشت:
