### ISSUE TITLE
Bad train/test split

### ISSUE THREAD

**Issue by raghakot** [davidsandberg/facenet#12]
In https://github.com/davidsandberg/facenet/blob/master/facenet/src/facenet.py#L540
You have split based on classes. I think it should be split within each class instead.

**Comment by davidsandberg** [comment]
Hi,
I have added the possibility (split_mode==SPLIT_IMAGES) to split the data based on images instead of classes. It looks like it works ok but i haven't ran the training for any longer time yet.
Depending on how the split_ratio is set it can happen that the number of images for some classes becomes very few, and then it will be impossible to use the class for validation. The code becomes a bit more complex due to this and i think there may be cases where this split gives strange validation results.
