### ISSUE TITLE
pretrained model for updated code

### ISSUE THREAD

**Issue by liorshk** [davidsandberg/facenet#212]
Hi,

Can you please upload a newer pretrained model for the updated code?
It currently fails on error: 
`Tensor name "incept4b/branch3_5x5/conv1x1/batch_norm/batch_norm/gamma" not found in checkpoint files`

**Comment by davidsandberg** [comment]
Hi,
I don't what code you are running and which pretrained model you are trying to load but the intention is that the model is loaded from a metagraph file to avoid this kind of incompatibility problems. See validate_on_lfw.py for example.

**Comment by liorshk** [comment]
Thanks for the response, I downloaded the model that you uploaded: 20170216-091149
I tried retraining it using "pretrained_model" argument in facenet_train_classifier.py and it failed with the error that I mentioned.

I don't want it just for inference, is it possible?

**Comment by liorshk** [comment]
Thanks for answering, I downloaded the pretrained model

**Comment by davidsandberg** [comment]
Hi,
It will not work out-of-the-box.
Even if you use the correct model definition (inception-resnet-v1) for the above model you will need to have the same number of classes in your dataset as I had when I trained the model. Otherwise it will be problem when loading the model.
Alternatively you can remove the last classification layer and prevent tensorflow from loading the parameters for that layer, but that will be some hands-on...

**Comment by davidsandberg** [comment]
I have added a script 'classifier.py' that can train a small classifier on the facenet features. There is also a wiki page showing how to use it. Hopefully that will help.
