### ISSUE TITLE
Tensor shape issue with different image size

### ISSUE THREAD

**Issue by christiansafka** [davidsandberg/facenet#274]
Hi, I am getting
`ValueError: Cannot feed value of shape (2, 415, 415, 3) for Tensor 'input:0', which has shape '(?, 160, 160, 3)'`
when running the classifier in train mode, passing in the image_size arg as 415.

I tried reshaping it
`images_placeholder = tf.reshape(tf.get_default_graph().get_tensor_by_name("input:0"), [args['batch_size'], args['image_size'], args['image_size'], 3])`
which resulted in this error:
`InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'batch_size' with dtype int32
	 [[Node: batch_size = Placeholder[dtype=DT_INT32, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

Any ideas?

Thanks!

**Comment by davidsandberg** [comment]
Hi,
Since the feature extraction CNN is trained on 160x160 pixel images it needs images of that size also when training the classifier. The easiest option for you would be to resize your images before feeding them to the CNN. The other option would be to train a new model for feature extraction. But that would of course take a lot more effort and you would need to have a large face dataset with 415x415 pixel images.

**Comment by christiansafka** [comment]
That's what I was thinking but 160 just seemed really low..  I will give it a try though, thanks
