### ISSUE TITLE
how to use my own trained model?

### ISSUE THREAD

**Issue by cqswxj2013** [davidsandberg/facenet#279]
stackoverflow : https://stackoverflow.com/questions/44017147/how-to-use-my-own-trained-model-with-facenet-implemented-in-tensorflow

**Comment by siebertlooije** [comment]
Hi,

So there are two ways how you can do this. 
1. https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images, here you can specify your own dataset to train the model and later on test the model. 
2. https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1.
Instead of using the CASIA dataset (datasets/casia/CASIA-maxpy-clean/). You can specify your own dataset to train the model. 

Error in stackoverflow : 
*"KeyError:** "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph.""*
The error in your stackoverflow is quite obvious, apparently you have trained a model that did not have that tensor. You can check this by printing the tensors in your graph. If this is not the case then you should removes this from the variables you want to restore.
I think you should take a look in the two possible options and first pull the latest version of the github because the facenet_train.py is renamed in the newest version.

**Comment by davidsandberg** [comment]
@cqswxj2013, it looks like you are are seeing issue #233.
Change from 
`images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")`
to
`images_placeholder = tf.get_default_graph().get_tensor_by_name("batch_join:0")`
