### ISSUE TITLE
classification using facenet

### ISSUE THREAD

**Issue by mrphoenix13** [davidsandberg/facenet#30]
I've tried to read your code. but I didn't get how you can classify an image.
Consider that you want to classify one image with this network. is there any simple way to feed the network with that picture and retrieve the class of that image?

**Comment by davidsandberg** [comment]
When the network is trained with the triplet loss loss function it is easy to compare two images and tell if the images are of the same person or not. The performance can then be evaluated on the LFW dataset which can be of classes that is previously unseen.
But if you want to do image classification this is not as straight forward. The best way is to replace the top layer of the model (i.e. the linear mapping to the 128-dimensional embedding) with a linear mapping to a vector with the same dimension as there are classes, and then calculate a loss using soft max.
I have recently started to work on this, mainly in order to get better filters, but it is far(!) from finished. But you can have a look at it on the branch `classifier_pretrain`. The facenet_train module can be found [here](https://github.com/davidsandberg/facenet/blob/classifier_pretrain/facenet/src/facenet_train.py).
The code seems to be running and learning something but that's all i can say...
