### ISSUE TITLE
Use the current model among different people.

### ISSUE THREAD

**Issue by ouyangbei** [davidsandberg/facenet#309]
When i apply it to the yellow race， I got a lower accuracy . The impact of race on the outcome is certainly great. So I must train my own models. Is that right?

**Comment by MaartenBloemen** [comment]
Can you tell how you tested that you get a lower accuracy on asian people? I'm quite interested to know if race actually makes a difference on the accuracy.

**Comment by ouyangbei** [comment]
@MaartenBloemen  When i use the model provided by MS-Celeb-1M，I got a lower accuracy on asian people, but there is a higher score on Caucasian.

**Comment by avikj** [comment]
There's obviously differences in facial structure between caucasian and asian people. Since FaceNet extracts features that distinguish between people, it makes sense that if trained on a dataset primarily of caucasians (like ms celeb 1m), it would extract features that help in distinguishing between caucasians. These features are probably slightly different than what would be used to distinguish between asians, and would be less accurate for different races; in fact, humans often suffer from seeing members of different races as all looking the same, because they have not been "trained" to distinguish with features for different races. @ouyangbei you probably need to train FaceNet on your own dataset with triplet loss.

**Comment by tonybaigang** [comment]
@avikj 
How to train FaceNet with my own dataset?
It's ok to follow the instruction of this article "https://github.com/davidsandberg/facenet/wiki/Triplet-loss-training"?
