### ISSUE TITLE
How to reload the pretrained model and modify its network structure to train my own datasets?

### ISSUE THREAD

**Issue by Victoria2333** [davidsandberg/facenet#421]
I want to train my own face datasets,but i don't konw how to deal with .pb,.ckpt,.meta files to visualize its net strcucture and parameter weights,the training methods can be found in relevant page.
Anybody could help me???
Thanks in advance~~~

**Comment by JianbangZ** [comment]
You will know the net structure from the code. 
Usually if you want to alter the net structure a lot of the modifications are in early layers, it's quite hard or impossible to reuse the pretrained model. The common way people try is only restoring the layers except from the last FC layer, so that they can use their own dataset with different class numbers

**Comment by Victoria2333** [comment]
Oh,i see,but which code shows the net structure???Or how could i restore the layers except from the last FC layer to adjust my own class numbers???
Thank you very much~~~

**Comment by Victoria2333** [comment]
I think there is no need to modify this network,just following the author's page about how to train your own datasets is OK
