### ISSUE TITLE
Hi How can I add the new person's embeddings to the old embeddings?

### ISSUE THREAD

**Issue by xvdehao** [davidsandberg/facenet#496]
Hi now I can get the embeddings.npy by export_embeddings.py
if I have got the 10 people faces embeddings, and I want to add a new person's  face embeddings
How should I handle the file (embeddings.npy)?

Really looking forward to your replying 
Thanks
 @Charles Jekel @davidsandberg

**Comment by cjekel** [comment]
If it's just a few images... it's probably easiest to just run export_embeddings.py again. 

However sometimes you may have thousands of images which you don't want to run again on... You can export the embeddings of just one set and run something like
```
import numpy as np
old = np.load('embeddings_old.npy')
new = np.load('embeddings_new.npy')
my_new_embeddings = np.vstack((old,new))
np.save('my_new_embeddings.npy', my_new_embeddings)
```
You'd use a similar code for the labels...

**Note:** careful with the name of your .npy files, if you leave export_embeddings.py on the defaults it will overwrite your previous embeddings.npy file

**Comment by xvdehao** [comment]
Thank you so much, thats exactly what I want.
And may I ask a question by the way whats the meaning of label_strings.npy, I note that it dosent been used in the whole process about SVM train model?

**Comment by cjekel** [comment]
That's because a lot classification implementations don't accept strings as labels, and instead require integers as labels. (scikit-learn SVM actually accepts either integers or strings http://scikit-learn.org/stable/modules/svm.html#classification )


Let's take a look at the following database of three people where a_person contains 2 images of someone, b_person contains 1 image of someone, and c_person contains 4 images of someone.

```
my_database
└───a_person
│   │   image00.jpg
│   │   image01.jpg
│   
└───b_person
│   │   image00.jpg
│   
└───c_person
│   │   image00.jpg
│   │   image01.jpg
│   │   image02.jpg
│   │   image03.jpg
```
labels will be the integer labels of the database (as used by many classification libraries), and in this case labels = [0,0,1,2,2,2,2]

label_stings will be the folder names from within the database (sometimes it makes more sense to have real string labels instead of integers), and in this case
label_strings = ['a_person', 'a_person', 'b_person', 'c_person','c_person','c_person','c_person']

**Comment by xvdehao** [comment]
Got it
Thats really helpful to me 
Thank you so much!
