### ISSUE TITLE
KeyError occurs when importing the meta file

### ISSUE THREAD

**Issue by NoobFang** [davidsandberg/facenet#58]
Hi,

After I download the pre-trained model "20161030-023650", I want to restore the model by load_model() in "facenet.py".  Unfortunately, a KeyError occurs:
-------------------
In [15]: facenet.load_model('20161030-023650/', meta_file, ckpt_file)

KeyError                                  Traceback (most recent call last)
<ipython-input-15-b99dba59f4f4> in <module>()
----> 1 facenet.load_model('20161030-023650/', meta_file, ckpt_file)

facenet.py in load_model(model_dir, meta_file, ckpt_file)
    468 def load_model(model_dir, meta_file, ckpt_file):
    469   model_dir_exp = os.path.expanduser(model_dir)
--> 470   saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file))
    471   saver.restore(tf.get_default_session(), os.path.join(model_dir_exp,ckpt_file))
    472 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.pyc in import_meta_graph(meta_graph_or_file)
   1456     return _import_meta_graph_def(meta_graph_or_file)
   1457   else:
-> 1458     return _import_meta_graph_def(read_meta_graph_file(meta_graph_or_file))
   1459 
   1460 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.pyc in _import_meta_graph_def(meta_graph_def)
   1346     producer_op_list = meta_graph_def.meta_info_def.stripped_op_list
   1347   importer.import_graph_def(meta_graph_def.graph_def, name="",
-> 1348                             producer_op_list=producer_op_list)
   1349 
   1350   # Restores all the other collections.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.pyc in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    250     for node in graph_def.node:
    251       # Set any default attr values that aren't present.
--> 252       op_def = op_dict[node.op]
    253       for attr_def in op_def.attr:
    254         key = attr_def.name

KeyError: u'RsqrtGrad'
----------------------------------------
I use Tensorflow 0.10 in Ubuntu, with CUDA 7.5 and CUDNN 4.
How can I solve this problem?

**Comment by davidsandberg** [comment]
I have exported [the model](https://drive.google.com/file/d/0B5MzpY9kBtDVVWtDUi1aS2t3VnM/view?usp=sharing) as a graphdef protobuf that can be evaluated with a new module `validate_on_lfw_new.py`. 
It should just be to download the model and point to it when running evaluation, something like
`python validate_on_lfw_new.py ~/datasets/lfw/lfw_mtcnnpy_160 ~/models/export/20161030-023650.pb`

**Comment by NoobFang** [comment]
That seems work for evaluation.

However, if the weights in .pb file is from a freezed graph, can I just import_graph_def it and re-train the model?

**Comment by davidsandberg** [comment]
If you want to retrain the model another alternative is to create the model programatically, i.e. by calling inference(...) for the model, like it's done in facenet_train_classifier.py. 
And then you can load the file containing the parameters, i.e. `model-20161030-023650.ckpt-80000` using saver.restore(...) in the same way as it's done in load_model(...).

**Comment by NoobFang** [comment]
OK, I get it now. Thanks for your explanation!

**Comment by xl94** [comment]
Which tensorflow version is the model trained for the create the graph file then?

**Comment by simplysimleprob** [comment]
Hi David,

First of all, thank you for sharing you great work.
I have a problem importing the meta file.
(I use Tensorflow 0.10 in Ubuntu 14.04 LTS, with CUDA 7.5 and CUDNN 5. )

1. when running validate_on_lfw.py, the below error is thrown.

Model directory: ../models/20161030-023650
Metagraph file: model-20161030-023650.meta
Checkpoint file: model-20161030-023650.ckpt-80000
Traceback (most recent call last):
  File "validate_on_lfw.py", line 89, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "validate_on_lfw.py", line 57, in main
    facenet.load_model(args.model_dir, meta_file, ckpt_file)
  File "/data/deep_learning/acl_work/facenet/src/facenet.py", line 469, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file))
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1458, in import_meta_graph
    return _import_meta_graph_def(read_meta_graph_file(meta_graph_or_file))
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1348, in _import_meta_graph_def
    producer_op_list=producer_op_list)
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 252, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'RsqrtGrad'

2. when running validate_on_lfw_new.py w/ your exported pb file, it also threw the below error.

E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'out_type' not in Op<name=Shape; signature=input:T -> output:int32; attr=T:type>; NodeDef: import/InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/moments/sufficient_statistics/Shape = Shape[T=DT_FLOAT, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](import/InceptionResnetV1/Conv2d_1a_3x3/Conv2D)
	 [[Node: import/InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/moments/sufficient_statistics/Shape = Shape[T=DT_FLOAT, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](import/InceptionResnetV1/Conv2d_1a_3x3/Conv2D)]]
Traceback (most recent call last):
  File "validate_on_lfw_new.py", line 87, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "validate_on_lfw_new.py", line 61, in main
    images_placeholder, phase_train_placeholder, embeddings, nrof_folds=args.lfw_nrof_folds)
  File "/data/deep_learning/acl_work/facenet/src/lfw.py", line 51, in validate
    emb_array[start_index:end_index,:] = sess.run(embeddings, feed_dict=feed_dict)
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: NodeDef mentions attr 'out_type' not in Op<name=Shape; signature=input:T -> output:int32; attr=T:type>; NodeDef: import/InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/moments/sufficient_statistics/Shape = Shape[T=DT_FLOAT, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](import/InceptionResnetV1/Conv2d_1a_3x3/Conv2D)
	 [[Node: import/InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/moments/sufficient_statistics/Shape = Shape[T=DT_FLOAT, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](import/InceptionResnetV1/Conv2d_1a_3x3/Conv2D)]]
Caused by op u'import/InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/moments/sufficient_statistics/Shape', defined at:
  File "validate_on_lfw_new.py", line 87, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "validate_on_lfw_new.py", line 50, in main
    return_elements=return_elements, name='import')
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 279, in import_graph_def
    op_def=op_def)
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/misunpar/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

Can you please help me on this issue?
Thank you so much.
