### ISSUE TITLE
Doubt regarding training on own dataset

### ISSUE THREAD

**Issue by mashrin** [davidsandberg/facenet#635]
As much as I know, Facenet is not a classifier that is trained to classify a face as belonging to a particular individual that it was trained on. Instead it is trained to find and quantify landmarks on faces in general. By comparing the face landmark quantification values (network inference output) on two images, it is possible to determine how likely the two faces are of the same person.
Kindly let me know if it's incorrect.

If it's true, I would like to know what is the benefit to- Train a classifier on own images?
How will it benefit?

I am asking this because I am using the pre-trained model and I am providing an image for the person whom I want to be recognised. Now, I am using the webcam to recognise that person and I am getting a really bad result!

**Comment by SiddhardhaSaran** [comment]
That's the very reason (your bad results)  why you want to train using your own images.The pre-trained model was trained on a large number of faces so that it will generalize to all other faces.
Since it isn't doing well on your images( not able to accurately get the features of your images), try training on your dataset.So that it will learn the features of your dataset and hopefully get better results.
